const D=window.DATA;let P=structuredClone(D.stock),C=structuredClone(D.cuts),H=[];const $=s=>document.querySelector(s),findP=c=>P.find(x=>x.code===c);
function show(id){document.querySelectorAll("main>section").forEach(x=>x.classList.add("hidden"));$("#"+id).classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.p===id));scrollTo(0,0)}document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>show(b.dataset.p));$("#printBtn").onclick=()=>print();
function render(){$("#bars").textContent=P.reduce((a,x)=>a+x.qty,0);$("#cutCount").textContent=C.filter(x=>x.status==="DOSTUPNÝ").reduce((a,x)=>a+x.qty,0);$("#moves").textContent=H.length;$("#stockT").innerHTML='<table><tr><th>Kód</th><th>Názov</th><th>Farba</th><th>Dĺžka</th><th>Ks</th></tr>'+P.map(x=>`<tr><td><b>${x.code}</b></td><td>${x.name}</td><td>${x.color}</td><td>${x.length}</td><td>${x.qty}</td></tr>`).join('')+'</table>';$("#cutsT").innerHTML='<table><tr><th>ID</th><th>Profil</th><th>Dĺžka</th><th>Ks</th><th>Stav</th></tr>'+C.map(x=>`<tr><td>${x.id}</td><td>${x.code}</td><td>${x.length}</td><td>${x.qty}</td><td>${x.status}</td></tr>`).join('')+'</table>';$("#histT").innerHTML=H.length?'<table><tr><th>Čas</th><th>Typ</th><th>Profil</th><th>Farba</th><th>Ks</th><th>Dĺžka</th><th>Zákazka</th></tr>'+H.map(x=>`<tr><td>${x.time}</td><td>${x.type}</td><td>${x.code}</td><td>${x.color||"—"}</td><td>${x.qty}</td><td>${x.length}</td><td>${x.job}</td></tr>`).join('')+'</table>':'Bez pohybov.';$("#jobT").innerHTML='<table><tr><th>Profil</th><th>Názov</th><th>Dĺžka</th><th>Ks</th></tr>'+D.famus.map(x=>`<tr><td>${x.code}</td><td>${x.name}</td><td>${x.length}</td><td>${x.qty}</td></tr>`).join('')+'</table>'}
function normalizeColor(s){return String(s||"").toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Z0-9]/g,"")}function parseCode(s){let a=s.trim().split("|");return a.length===3&&a[0]==="LANGAS"?{code:a[1],color:a[2]}:null}function addCut(p,len,qty){C.push({id:"ODR-"+String(C.length+1).padStart(3,"0"),code:p.code,length:len,qty,status:"DOSTUPNÝ"})}
function issueOne(p,want,job){const k=5,min=500;let a=C.filter(x=>x.code===p.code&&x.status==="DOSTUPNÝ"&&x.qty>0&&x.length>=want+k).sort((x,y)=>x.length-y.length);if(a.length){let c=a[0],old=c.length;c.qty--;if(!c.qty)c.status="SPOTREBOVANÝ";let r=old-want-k;if(r>=min)addCut(p,r,1);H.unshift({time:new Date().toLocaleString("sk-SK"),type:"ODBER-ODREZOK",code:p.code,color:p.color,qty:1,length:want,job});return `Použitý odrezok ${old} mm → ${want} + 5 mm${r>=min?` → nový odrezok ${r} mm`:" → zvyšok odpad"}.`}if(!p.qty)return"NEDOSTATOK: nie je celá tyč.";p.qty--;let r=p.length-want-k;if(r<0){p.qty++;return"NEDOSTATOK: požadovaná dĺžka je väčšia než celá tyč."}if(r>=min)addCut(p,r,1);H.unshift({time:new Date().toLocaleString("sk-SK"),type:"ODBER-CELÁ TYČ",code:p.code,color:p.color,qty:1,length:want,job});return `Otvorená celá tyč ${p.length} mm → ${want} + 5 mm${r>=min?` → nový odrezok ${r} mm`:" → zvyšok odpad"}.`}
$("#confirmScan").onclick=()=>{
  let q=parseCode($("#scanCode").value),qty=+$("#scanQty").value,entered=+$("#reqLen").value,job=$("#scanJob").value||"Bez zákazky",mode=$("#lengthMode").value;
  if(!q)return $("#scanResult").innerHTML='<p class="bad">Neplatný kód.</p>';
  let p=P.find(x=>x.code===q.code&&normalizeColor(x.color)===normalizeColor(q.color));
  if(!p)return $("#scanResult").innerHTML='<p class="bad">Profil/farba nie je v sklade.</p>';
  let m=[];
  if($("#operation").value==="PRÍJEM"){
    let receivedLength=mode==="auto"?p.length:entered;
    if(!receivedLength||receivedLength<=0)return $("#scanResult").innerHTML='<p class="bad">Zadaj platnú dĺžku.</p>';
    if(receivedLength===p.length){p.qty+=qty}
    else{addCut(p,receivedLength,qty)}
    H.unshift({time:new Date().toLocaleString("sk-SK"),type:"PRÍJEM",code:p.code,color:p.color,qty,length:receivedLength,job});
    m.push(`Prijaté ${qty} ks · ${p.code} · ${p.color} · ${receivedLength} mm.`);
  }else{
    let want=entered;
    if(!want||want<=0)return $("#scanResult").innerHTML='<p class="bad">Zadaj požadovanú výrobnú dĺžku.</p>';
    for(let i=0;i<qty;i++)m.push(issueOne(p,want,job));
  }
  $("#scanResult").innerHTML='<div class="note">'+m.join("<br>")+'</div>';render()
};
let qrStream=null,qrRunning=false;
function stopScanner(){qrRunning=false;if(qrStream){qrStream.getTracks().forEach(t=>t.stop());qrStream=null}$("#video").classList.add("hidden")}
function scanFrame(){if(!qrRunning)return;const v=$("#video");if(v.readyState>=2&&v.videoWidth){const cv=document.createElement("canvas");cv.width=v.videoWidth;cv.height=v.videoHeight;const ctx=cv.getContext("2d",{willReadFrequently:true});ctx.drawImage(v,0,0,cv.width,cv.height);const im=ctx.getImageData(0,0,cv.width,cv.height);const q=window.jsQR?jsQR(im.data,im.width,im.height,{inversionAttempts:"dontInvert"}):null;if(q&&q.data){const parsed=parseCode(q.data);if(parsed&&findP(parsed.code)){$("#scanCode").value=q.data;$("#camMsg").innerHTML='<span class="ok">Načítané: '+parsed.code+' · '+parsed.color+'</span>';stopScanner();if(navigator.vibrate)navigator.vibrate(120);return}else{$("#camMsg").innerHTML='<span class="bad">QR bol načítaný, ale nie je to platný LANGAS skladový kód.</span>'}}}requestAnimationFrame(scanFrame)}
$("#camera").onclick=async()=>{try{stopScanner();if(!window.jsQR)throw Error("QR dekodér sa nenačítal.");qrStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});$("#video").srcObject=qrStream;$("#video").classList.remove("hidden");await $("#video").play();qrRunning=true;$("#camMsg").textContent="Namier kameru na LANGAS QR kód…";requestAnimationFrame(scanFrame)}catch(e){$("#camMsg").textContent="Kameru/QR sa nepodarilo spustiť: "+e.message}};
document.querySelectorAll('input[name="gut"]').forEach(r=>r.onchange=()=>{$("#customGut").classList.toggle("hidden",document.querySelector('input[name="gut"]:checked').value!=="custom");checkGut()});document.querySelectorAll(".glen").forEach(x=>x.oninput=checkGut);function checkGut(){let s=[...document.querySelectorAll(".glen")].reduce((a,x)=>a+(+x.value||0),0),n=11992;$("#gcheck").innerHTML=s===n?'<span class="ok">Súčet sedí.</span>':`<span class="bad">Súčet ${s}; požadované ${n}; rozdiel ${n-s}.</span>`}
function evalJob(){return D.famus.map(x=>{let p=findP(x.code),n=x.length*x.qty,a=(p?p.length*p.qty:0)+C.filter(c=>c.code===x.code&&c.status==="DOSTUPNÝ").reduce((s,c)=>s+c.length*c.qty,0);return[x.code,x.name,(n/1000).toFixed(2),(a/1000).toFixed(2),a>=n?"OK":"NEDOSTATOK"]})}
$("#evaluate").onclick=()=>{if(document.querySelector('input[name="gut"]:checked').value==="custom"&&[...document.querySelectorAll(".glen")].reduce((a,x)=>a+(+x.value||0),0)!==11992)return alert("Vlastné dĺžky žľabu nemajú správny súčet.");let r=evalJob();$("#evaluation").innerHTML='<h3>Kontrola dostupnosti</h3><div class="scroll"><table><tr><th>Profil</th><th>Názov</th><th>Potrebné bm</th><th>Dostupné bm</th><th>Stav</th></tr>'+r.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td class="${x[4]==="OK"?"ok":"bad"}">${x[4]}</td></tr>`).join('')+'</table></div><div class="actions"><button id="genPrint">Vytvoriť výrobný list</button></div>';$("#genPrint").onclick=makePrint};
function makePrint(){let g=document.querySelector('input[name="gut"]:checked').value==="custom"?[...document.querySelectorAll(".glen")].map(x=>+x.value):[4000,4000,3992];$("#printBody").innerHTML=D.famus.map(x=>`<h3>${x.code} – ${x.name}</h3><p>${x.qty} × ${x.length} mm</p>`).join('')+`<h3>W.2309 – delenie žľabu</h3><p>${g.join(" + ")} mm</p>`;show("print")}render();checkGut();